---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "",
  dev = "svg",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# c13ms

<!-- badges: start -->
<!-- badges: end -->

Analysis of isotope-labelled metabolomics data


```{r, include = FALSE}

library(c13ms)
#library(magrittr)

```



## Introduction

```{r, results='hide', message=FALSE, warning=FALSE}

C13 <- exampleTracerExperiment(nsamples = 6, nmets = 5)

colnames(C13)
metnames(C13)
rownames(C13)

colData(C13)
C13$group

C13 %>% subset(group == "A")
C13groups <- split(C13, by = ~ group)
C13 <- with(C13groups, A + B)

metData(C13)
isoData(C13)

assay(C13, "raw")
sumMets(C13, assay = "raw")

```


## Workflow

A typical analysis workflow may look like as demonstrated below:

```{r, message=FALSE, warning=FALSE}

C13 %<>% impute(assay = "raw")
C13 %<>% correctIso(assay = "imp")
C13 %<>% normalize(method = ~ COLSUM, assay = "corr")

assay(C13, "mid") <- MID(C13)
assay(C13, "frac", type = "met") <- isoEnrichment(C13)
assay(C13, "norm", type = "met") <- sumMets(C13)

contrasts <- list(groupBvsA = list("group" = c("B", "A")))

C13 %<>% diffTest(contrasts = contrasts, formula = ~ group, type = "met", assay = "norm", method = "ttest")
C13 %<>% diffTest(contrasts = contrasts, formula = ~ group, type = "met", assay = "frac", method = "beta")
C13 %<>% diffTest(contrasts = contrasts, formula = ~ group, type = "iso",  assay = "mid", method = "beta")

results(C13, "iso", "mid", "beta") %>% head(10)

```


## Visualization

```{r}

isoplot(C13, mets = metnames(C13)[1])

```


